package com.pason.alertengine.domain.model;

import com.pason.alertengine.domain.condition.AlertCondition;
import java.util.Objects;
import java.util.Optional;

/**
 * A configurable rule that defines when an alert should be triggered.
 *
 * <p>Each rule binds a sensor type to an alert condition and severity level.
 * When the alert engine processes a reading, it evaluates all enabled rules
 * whose sensor type matches the reading's type. If the condition evaluates
 * to true, an alert is generated with the rule's configured severity.</p>
 *
 * <p>Rules are immutable once constructed. Use the {@link Builder} to create:</p>
 * <pre>{@code
 * AlertRule rule = AlertRule.builder()
 *     .name("Critical Pressure")
 *     .sensorType(SensorType.PRESSURE)
 *     .condition(new ThresholdExceededCondition(3000, GREATER_THAN))
 *     .severity(AlertSeverity.CRITICAL)
 *     .build();
 * }</pre>
 */
public final class AlertRule {

  private final Long id;
  private final String name;
  private final SensorType sensorType;
  private final AlertCondition condition;
  private final AlertSeverity severity;
  private final boolean enabled;

  private AlertRule(Builder builder) {
    this.id = builder.id;
    this.name = builder.name;
    this.sensorType = builder.sensorType;
    this.condition = builder.condition;
    this.severity = builder.severity;
    this.enabled = builder.enabled;
  }

  /**
   * Creates a new {@link Builder} for constructing an AlertRule.
   *
   * @return a new Builder instance
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the rule's database ID, if it has been persisted.
   *
   * @return the ID wrapped in an Optional, or empty if the rule is transient
   */
  public Optional<Long> getId() {
    return Optional.ofNullable(id);
  }

  /** Returns the human-readable name of this rule. */
  public String getName() {
    return name;
  }

  /** Returns the sensor type this rule applies to. */
  public SensorType getSensorType() {
    return sensorType;
  }

  /** Returns the condition that determines when this rule triggers. */
  public AlertCondition getCondition() {
    return condition;
  }

  /** Returns the severity level assigned to alerts generated by this rule. */
  public AlertSeverity getSeverity() {
    return severity;
  }

  /** Returns whether this rule is currently active for evaluation. */
  public boolean isEnabled() {
    return enabled;
  }

  /** {@inheritDoc} Equality is based on ID and name. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertRule alertRule = (AlertRule) o;
    return Objects.equals(id, alertRule.id) && Objects.equals(name, alertRule.name);
  }

  /** {@inheritDoc} Hash is computed from ID and name. */
  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }

  /** {@inheritDoc} Returns a human-readable summary of this rule. */
  @Override
  public String toString() {
    return String.format("AlertRule{name=%s, sensor=%s, severity=%s, enabled=%s, condition=%s}",
        name, sensorType, severity, enabled, condition.describe());
  }

  /** Builder for constructing immutable {@link AlertRule} instances. */
  public static class Builder {

    private Long id;
    private String name;
    private SensorType sensorType;
    private AlertCondition condition;
    private AlertSeverity severity;
    private boolean enabled = true;

    /** Sets the database ID for a persisted rule. */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /** Sets the human-readable name of this rule. */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /** Sets the sensor type this rule applies to. */
    public Builder sensorType(SensorType sensorType) {
      this.sensorType = sensorType;
      return this;
    }

    /** Sets the condition that determines when this rule triggers. */
    public Builder condition(AlertCondition condition) {
      this.condition = condition;
      return this;
    }

    /** Sets the severity level assigned to alerts generated by this rule. */
    public Builder severity(AlertSeverity severity) {
      this.severity = severity;
      return this;
    }

    /** Sets whether this rule is active for evaluation (defaults to true). */
    public Builder enabled(boolean enabled) {
      this.enabled = enabled;
      return this;
    }

    /**
     * Builds the alert rule instance.
     *
     * @return a new immutable AlertRule
     * @throws IllegalStateException if required fields are missing
     */
    public AlertRule build() {
      if (name == null || name.isBlank()) {
        throw new IllegalStateException("name is required");
      }
      if (sensorType == null) {
        throw new IllegalStateException("sensorType is required");
      }
      if (condition == null) {
        throw new IllegalStateException("condition is required");
      }
      if (severity == null) {
        throw new IllegalStateException("severity is required");
      }
      return new AlertRule(this);
    }
  }
}
