spring:
  datasource:
    url: jdbc:tc:mysql:8.0:///alert_engine_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  flyway:
    enabled: true

logging:
  level:
    com.pason.alertengine: DEBUG
