spring:
  datasource:
    url: ${TEST_DATASOURCE_URL:jdbc:tc:mysql:8.0:///alert_engine_test}
    driver-class-name: ${TEST_DATASOURCE_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

logging:
  level:
    com.pason.alertengine: DEBUG
